"""
Coverage dicts derived from Gavi shipments + actuals + WUENIC target ages.
Auto-generated by scripts/compute_coverage.py -- do not hand-edit.
"""

vx_coverage_shipped = {
    'bangladesh'    : 0.93,
    'burkina faso'  : 0.55,
    'cambodia'      : 0.44,
    'cameroon'      : 0.19,
    'cote divoire'  : 0.27,
    'ethiopia'      : 0.90,
    'gambia'        : 0.56,
    'laos'          : 0.98,
    'mali'          : 0.14,
    'mozambique'    : 0.47,
    'myanmar'       : 0.47,
    'nigeria'       : 0.87,
    'sierra leone'  : 0.20,
    'tanzania'      : 0.56,
    'togo'          : 0.94,
    'zambia'        : 0.89,
}

vx_coverage_actual = {
    'bangladesh'    : 0.86,
    'burkina faso'  : 0.37,
    'cambodia'      : 0.33,
    'cameroon'      : 0.20,
    'cote divoire'  : 0.38,
    'ethiopia'      : 0.54,
    'gambia'        : 0.53,
    'laos'          : 0.45,
    'mali'          : 0.03,
    'mozambique'    : 0.46,
    'myanmar'       : 0.55,
    'nigeria'       : 0.79,
    'sierra leone'  : 0.31,
    'tanzania'      : 0.95,
    'togo'          : 0.50,
    'zambia'        : 0.54,
}

vx_coverage_cf = {
    'bangladesh'    : 0.34,
    'burkina faso'  : 0.21,
    'cambodia'      : 0.17,
    'cameroon'      : 0.07,
    'cote divoire'  : 0.10,
    'ethiopia'      : 0.47,
    'gambia'        : 0.22,
    'laos'          : 0.52,
    'mali'          : 0.05,
    'mozambique'    : 0.19,
    'myanmar'       : 0.18,
    'nigeria'       : 0.33,
    'sierra leone'  : 0.10,
    'tanzania'      : 0.30,
    'togo'          : 0.42,
    'zambia'        : 0.45,
}
